### PR TITLE
Fixed warning: preg_match_all()

### PR DESCRIPTION
**Pull request by ashrafhesham-92**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7815

Created  PR as per @grey-rsi request.

### CODE REVIEW

**Comment by strategio** [comment]
@grey-rsi, could you please add a new test case for your fix => https://github.com/OnTheGoSystems/wpml-page-builders-elementor/blob/master/tests/phpunit/tests/test-wpml-elementor-urls.php#L116

You can probably reuse one test and set a data provider.

**Review by dgwatkins — DISMISSED** [review]
Looks good :+1:

**Comment by ghost** [comment]
@strategio done

**Review by strategio — DISMISSED** [review]
+1 @grey-rsi

**Pull request merged**
