### PR TITLE
Add support for Author Box widget

### PR DESCRIPTION
**Pull request by amElnagdy**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7298

### CODE REVIEW

**Review by dgwatkins — DISMISSED** [review]
@amElnagdy 👍

**Comment by dgwatkins** [comment]
@amElnagdy Take a look at failing tests to see whats up?

**Comment by amElnagdy** [comment]
Looking, it's something with the new `field_id`. Trying to fix it.

**Comment by amElnagdy** [comment]
@strategio can you please have a look here? The test is failing, I've tried [this](https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/111/commits/e9440792d0753c77d043a3bf7e18c8960f711588) but it's not working out.

**Comment by strategio** [comment]
@amElnagdy, you can just remove your test. As I said before, this is a configuration made of static data, it makes no sense to have unit tests on this. Hopefully soon it will be all in a XML config file.

**Review by dgwatkins — DISMISSED** [review]
:+1:

**Review by strategio — DISMISSED** [review]
+1 @amElnagdy

**Pull request merged**
