### PR TITLE
Setting Image Box link to be translatable

### PR DESCRIPTION
**Pull request by amElnagdy**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6724

### CODE REVIEW

**Comment by amElnagdy** [comment]
@OnTheGoSystems/wpml I have no clue why the test is failing. The changes are simple.

**Comment by strategio** [comment]
@amElnagdy, the test method which is failing is pretty complex... I just had a look and I think you should insert this on line 116:

https://github.com/OnTheGoSystems/wpml-page-builders-elementor/blob/339fb0e162d470fc5990ccdc6cb38c41c5eca2c4/tests/phpunit/tests/test-wpml-elementor-translatable-nodes.php#L116)

```php
if ( 'image-box' === $type ) {
	$string = $strings[2];
}
```

Not very smart, but it should do the trick.

**Comment by amElnagdy** [comment]
Thanks @strategio, passed.

**Review by strategio — DISMISSED** [review]
+1 @amElnagdy

**Review by andreasciamanna — CHANGES_REQUESTED** [review]
@amElnagdy can you please rebase?

**Comment by andreasciamanna** [comment]
@amElnagdy this PR still look wrong.
I suggest you reset your local branch to **master** and then cherry-pick your commits.
If you have troubles doing that, I can help you: just ping me tomorrow.

**Comment by amElnagdy** [comment]
@andreasciamanna I just did what you're suggesting 
```
git reset --hard origin/master
git cherry-pick {commit-hashs}
```
I don't mind ignoring this PR and re-do everything again in a new and clean PR.

**Comment by andreasciamanna** [comment]
> I just did what you're suggesting
> 
> ```
> git reset --hard origin/master
> git cherry-pick {commit-hashs}
> ```

Did you push the changes? Because I still see 24 commits in this PR?
If you didn't push yet, please use `git push --force-with-lease` or create a new branch from it and a new PR.
The end result should be a PR with just your commits.

> I don't mind ignoring this PR and re-do everything again in a new and clean PR.

No need to start from scratch, but you can create a new branch+PR as I just explained.

**Pull request closed without merging**
