### PR TITLE
Fix condition to detect if a post uses Elementor's page builder

### PR DESCRIPTION
**Pull request by strategio**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6929

### CODE REVIEW

**Review by dgwatkins — DISMISSED** [review]
looks good

**Review by dgwatkins — DISMISSED** [review]

**Comment by strategio** [comment]
@dgwatkins, I usually create my PR and review it myself before to call for reviews.

Please check it again.

**Comment by dgwatkins** [comment]
You're right, you didn't call for review :-)

:+1:

**Comment by strategio** [comment]
@OnTheGoSystems/wpml

**Review by kagg-design — DISMISSED** [review]
+1 @strategio

**Comment by strategio** [comment]
@dgwatkins, @kagg-design,

Eventually, I had to fix one more thing, please check the last commit https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/98/commits/91141082a882634f10ee1729a19dff9223309ba1.

**Review by dgwatkins — DISMISSED** [review]

**Review by kagg-design — DISMISSED** [review]
+1 @strategio

**Pull request merged**
