### PR TITLE
[Elementor] Confusing setting for Language Switcher widget #138

### PR DESCRIPTION
**Pull request by kkarpieszuk**
When selecting the "custom" language switcher, the specific settings are controled from WPML > Langauges > Custom Language Switcher

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7740

### CODE REVIEW

**Comment by kkarpieszuk** [comment]
@strategio please continue here what we started in https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/138

The same code changes except:
- now targeting master, not develop
- no issues with tabs
- rephrased commit message

**Review by strategio — APPROVED** [review]
+1 @kkarpieszuk

**Comment by kkarpieszuk** [comment]
Thanks, Comp team, please provide another review

**Review by dgwatkins — APPROVED** [review]
@kkarpieszuk :+1:

**Pull request merged**
