### PR TITLE
Improve `DataConvert::unserialize` to be tolerant with already unserialized data

### PR DESCRIPTION
**Pull request by strategio**
This happens with imported templates provide by Astra theme.

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-8775

Added an extra commit to fix a non-related unit test.

### CODE REVIEW

**Review by dgwatkins — DISMISSED** [review]
Everything is perfect :+1:

**Comment by strategio** [comment]
@dgwatkins, I added one more commit, please check again.

Our PB code has some flaw, the "unserialize" code can receive both single or multiple post meta, it ends up decoding the JSON string. And that make impossible to know what we are converting when we receive a full multi-dimensional array... So my last commit is improving the code that is directly affecting us, even though there would be more to fix including in the main PB package (but then it's risky now).

**Review by dgwatkins — APPROVED** [review]
@strategio it still looks good

**Comment by strategio** [comment]
I close as "won't fix" for now.

**Pull request closed without merging**
