### PR TITLE
[Elementor] Confusing setting for Language Switcher widget

### PR DESCRIPTION
**Pull request by kkarpieszuk**
- added conditions for displaying link_current

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7740

### CODE REVIEW

**Comment by kkarpieszuk** [comment]
@OnTheGoSystems/compatibility please review

**Comment by strategio** [comment]
@kkarpieszuk, I have some general comments:
1. The tests are failing, could you please check it?
2. Could you improve the commit message (long description). Maybe something like "When selecting the "custom" language switcher, the specific settings are controled from WPML > Langauges > Custom Language Switcher".
3. Could you check why we have changes in the tabs size? A commit like this one should not change the tabs. If the tabs are initially wrong, it's OK to change but maybe in a separate commit.

**Comment by strategio** [comment]
@kkarpieszuk, the tests are failing on Github Actions due to a change in the setup. It's also happening on other projects and I'll [check this](https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-175).

**Comment by strategio** [comment]
@kkarpieszuk, I fixed the tests on CI and rebased your branch on it, and it's passing now.

BTW, I believe the target branch should be `master`. This package is currently going into WPML Core so we need to follow the guidelines for it. Once it will be in the new Page Builder plugin (with its own dev cycle) we will be able to apply the strategy we use for other glue plugins.

**Comment by kkarpieszuk** [comment]
Pierre, because of all the issues listed below I created new merge request
https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/139

- wrong tabs: I had a wrong settings in my phpstorm (new computer, still configuring)
- wrong commit message
- wrong target

I thought this will be quicker and cleaner to open new MR

**Pull request closed without merging**
