### PR TITLE
compsupp-3150 - Add missing Elementor Form elements

### PR DESCRIPTION
**Pull request by amElnagdy**
This is coming from https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-3150

PS: The online documentation we have is far from being helpful :)

### CODE REVIEW

**Comment by adrianosferreira** [comment]
@amElnagdy please also adjust the test `Test_WPML_Elementor_Form`. It should be easy, just add your new fields there, otherwise, it will fail. I would add them if I could, but I can't push for your branch.

**Review by adrianosferreira — DISMISSED** [review]
Looks good, +1.

**Review by adrianosferreira — DISMISSED** [review]
Looks good, +1.

**Comment by adrianosferreira** [comment]
@amElnagdy tests failing:
https://scrutinizer-ci.com/g/OnTheGoSystems/wpml-page-builders-elementor/inspections/7c2a26f6-0d99-4061-81d4-b7bb2ca21215

**Comment by amElnagdy** [comment]
@adrianosferreira I did not update the tests. Updated. 

I don't know much about these tests, but it's failing again. As far as I can see, the test is failing due to these changes https://github.com/OnTheGoSystems/wpml-page-builders-elementor/commit/7de11f44d07af6f78d7ff07555284a8f6832cfaf

**Comment by adrianosferreira** [comment]
@amElnagdy you must fix the test `Test_WPML_Elementor_Data_Settings:: it_gets_field_to_copy` and add the `_elementor_template_widget_type` in the array.

**Review by adrianosferreira — APPROVED** [review]
Looks good @amElnagdy, thanks. +1

**Pull request merged**
