### PR TITLE
Adding new Elementor widget: Post Navigation

### PR DESCRIPTION
**Pull request by amElnagdy**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6726

### CODE REVIEW

**Review by andreasciamanna — CHANGES_REQUESTED** [review]
@amElnagdy can you please resolve the conflicts?

**Review by andreasciamanna — DISMISSED** [review]

**Comment by andreasciamanna** [comment]
@OnTheGoSystems/wpml please review

**Review by strategio — DISMISSED** [review]

**Comment by andreasciamanna** [comment]
@amElnagdy you probably need one more rebase, then you only need to move the ticket to "Testing".

**Comment by dimitrismitsis** [comment]
@amElnagdy please take care of properly rebasing here to `origin/master`  
The branch is quite messed up right now, the rebasing hasn't been done properly and the conflict resolving shouldn't happen as separate commits.  

In case you find it hard to resolve all these, please reset to `origin/master` and apply your changes again.

**Comment by amElnagdy** [comment]
Creating a new PR

**Pull request closed without merging**
