### PR TITLE
Change the string Drop Down to Custom in the Language Switcher widget

### PR DESCRIPTION
**Pull request by amElnagdy**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmldoc-987

### CODE REVIEW

**Comment by amElnagdy** [comment]
@OnTheGoSystems/wpml please check this quick change.

**Review by andreasciamanna — CHANGES_REQUESTED** [review]
@amElnagdy 

The code looks ok.

However, there are other issues:

- Please look at [this discussion](https://chat.onthegosystems.com/otgs/pl/snq4kzbz5jn79pwm3obhsajxmc) on how to write a commit message.
- The YT ticket is a wpmldoc ticket: anything requiring changes in the code must belong to a product. All the `wpml-page-builders*` libraries belong to **wpmlcore**.

Please fix these two issues.

**Comment by amElnagdy** [comment]
Thanks @andreasciamanna. I'm closing this one as I opened a new one here https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/97

**Comment by andreasciamanna** [comment]
> Thanks @andreasciamanna. I'm closing this one as I opened a new one here #97

@amElnagdy that wasn't really needed. You could have just updated the branch and kept the same PR.

Anyway, we can continue in the other PR.

**Pull request closed without merging**
