### PR TITLE
Translate Cards Read More text in Posts module

### PR DESCRIPTION
**Pull request by adrianosferreira**
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-3347
It was missed.

### CODE REVIEW

**Comment by adrianosferreira** [comment]
@dimitrismitsis this got tested by Comp team already, should we merge it directly?

**Comment by adrianosferreira** [comment]
@dimitrismitsis ups, tests are failing, fixing...

**Review by andreasciamanna — APPROVED** [review]
@adrianosferreira I see nothing wrong here.

**Comment by adrianosferreira** [comment]
@andreasciamanna I don't know where I saw it failing yesterday. I guess we can merge it already as it was tested by Comp team.

**Pull request merged**
